### ISSUE TITLE
Dashboard not loading properly

### ISSUE THREAD

**Issue by cheetoblue** [Steem-FOSSbot/steem-fossbot-voter#102]
I seem to be getting this error when setting the bot up on one of my accounts. I only seem to get it when I make the voting account an account with a "." in the name. If I change the account to one without a "." in the name then it all works fine. Change it back and I get this as the dashboard screen again.

<img width="441" alt="screen shot 2017-08-17 at 11 16 38 pm" src="https://user-images.githubusercontent.com/25654629/29599809-76de554e-87d2-11e7-897b-8414de3b77e1.png">

**Comment by bobinson** [comment]
This is happening right now for my installation on heroku, docker on Ubuntu and Docker on MacOS

**Comment by DrakahnF** [comment]
An update, this morning I loaded it up out of habit and it is inexplicably working.

**Comment by thrize** [comment]
Well well, do you know what commit you're running from @DrakahnF ?

**Comment by thrize** [comment]
In a surprise move it looks like Steemit have booted up their websocket on wss://steemd.steemit.com again, probably because it broke everything. I'm sure we'll get a stern warning from @steemitdev but for the moment the bot is working. I'll make an announcement.

Rejoice!

**Comment by DrakahnF** [comment]
Latest / 67f3f75

**Comment by bobinson** [comment]
@thrize - appreciate the update. So much time wasted over this! appreciate your efforts.

**Comment by thrize** [comment]
Well I have to eat my words because it's steemd.steemit.com is offline again.

**Comment by bobinson** [comment]
bad - I will be available to test (same user name on discord and steemit.chat)

**Comment by thrize** [comment]
Pretty sure this is the same issue as #93, going to close as a duplicate

**Comment by bobinson** [comment]
docker method failing - on macOS and Ubunu GNU/Linux : anything to with the git merge ?

1. **run.sh update output**

```
updating Voter code...
HEAD is now at 79e4ade Merge branch 'master' into docker-develop
remote: Counting objects: 11, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 11 (delta 6), reused 11 (delta 6), pack-reused 0
Unpacking objects: 100% (11/11), done.
From https://github.com/Steem-FOSSbot/steem-fossbot-voter
   67f3f75..a533372  master     -> origin/master
 * [new branch]      thrize/patch-0-2-9-2 -> origin/thrize/patch-0-2-9-2
restoring setup files...
Voter docker update finished!

```

**git branch output:**

* (HEAD detached at 79e4ade)
  master

**Comment by bobinson** [comment]
removed all the related files and did a fresh install and the bot works now!
