### ISSUE TITLE
Vote on Comments - Feature request

### ISSUE THREAD

**Issue by Cam-B** [Steem-FOSSbot/steem-fossbot-voter#104]
Hi. I would like to ad this request to the list. We've talked about it on Steem briefly. 

It would be great if we could include comments as votable posts in FOSSbot.

I imagine I would run 1 instance that would vote on posts with 1 algorithm and then another bot instance that would vote on comments with a different algorithm and less voting weight.

**Comment by thrize** [comment]
Good idea, but that would be your choice. I think if the feature was implemented it should have three settings:

1. Vote on posts only
2. Vote on comments only
3. Vote on both posts and comments

However perhaps you should have a think about if there are any other special requirements for comment voting. There can be many many comments for one post for example.

**Comment by Cam-B** [comment]
Thank you for accepting the suggestion. If I come up with any more ideas for special requirements I will post them here. 

Adding the three options you suggest would make it easier than having to run separate bots with different configurations. Good point!

**Comment by NickDavison** [comment]
I would also love to see this added, any update on progress?

**Comment by thrize** [comment]
No @NickDavison , but I'm getting back to this project now. See my Steemit profile (at)personz soon for an update.

**Comment by thrize** [comment]
I'm thinking about this now for next phase of development after 0.3 maintenance release.

Firstly I think this relies on the improvements which are to happen in #96, sequential post processing.

Next, this will greatly increase processing time for posts. @Cam-B do you have any thoughts on this issue? Are you happy for it to take a very long time or should some kind of screening or filtering be applied?

**Comment by Cam-B** [comment]
@thrize Thanks for asking. I think that if we want to process comments we have to accept that it takes longer. Other than the filters FOSSbot already has I have no further suggestions at the moment.

**Comment by thrize** [comment]
Thanks for you input

**Comment by Cam-B** [comment]
I'm glad you're back.

**Comment by thrize** [comment]
I thought about this some more and I think it's not a good idea to implement. I'm involved in some anti-spam and scam projects and comment self voting is a huge problem on the platform. If I add this I've given people a tool to create a comment self voting bot net. I'm going to have to reject this feature.
