### ISSUE TITLE
Feature request: follow trusted curators votes. 

### ISSUE THREAD

**Issue by Cam-B** [Steem-FOSSbot/steem-fossbot-voter#105]
Another feature some closed source bots are profiting from is to:

Vote for posts that whitelisted accounts have voted for & don't vote if blacklisted account has voted for post.

This would be a great addition to FOSSbot. As always every feature we can add to this open source bot might help eliminate the unfair advantage some bot users have on Steem.

How do others feel?

**Comment by thrize** [comment]
This is actually possible now @Cam-B with some combination of the following metrics:

* ```post_up_voted_num_whitelisted```
* ```post_up_voted_num_blacklisted```
* ```post_up_voted_any_whitelisted```
* ```post_up_voted_any_blacklisted```

I presume by vote you mean up vote and also that you intend to be strict about it and don't want to vote for a post which _any_ blacklisted account has voted for even if _any_ whitelisted account voted for it.

In that case you would use these two metric with opposite weights, e.g.:

* ```post_up_voted_any_whitelisted```, weight = ```100```
* ```post_up_voted_any_blacklisted```, weight = ```-100```

**Comment by thrize** [comment]
Closed, no feature required to implement this use case

**Comment by thrize** [comment]
Hey @Cam-B by the way, this might make a good Steemit post. Just sayin' 😉

**Comment by Cam-B** [comment]
Awesome! And thanks for the suggestion. I will make a post including this once I have finally understood the metrics better. 

I'm opened a new issue with some more detailed questions. 
https://github.com/Steem-FOSSbot/steem-fossbot-voter/issues/107
