### ISSUE TITLE
Score calculation metrics.

### ISSUE THREAD

**Issue by Cam-B** [Steem-FOSSbot/steem-fossbot-voter#107]
I am having trouble understanding how the algorithm weights work to calculate score. 
I have read your "usage guide" and your page on "Algorithm and metrics" multiple times. 

https://github.com/Steem-FOSSbot/steem-fossbot-voter/blob/master/docs/usage-guide.md
https://github.com/Steem-FOSSbot/steem-fossbot-voter/blob/master/docs/algorithm.md

I think I understand the polynomial you dsecribe.
s = w[1]*m[1] + w[2]*m[2] + ... + w[n-1]*m[n-1] + w[n]*m[n]

My first question would be why we are using a negative value in the word count. this seems like it would lower the score with every extra word.

I'm guessing I am not understanding something deeper though.

**I'll use your first algorithm to base my questions from. I'll explain how I understand the metrics and hopefully you can point out what I'm not getting.** 

>  post_num_words in range 200 to 600, weight = -0.5

if the post contains between 200 and 600 words 
then -0.5 per word is added to the score. 

if the post contains more or less than 200-600 words it is ignored 

    

>  post_num_links_image in range 0 to 5, weight = 10

if the post contains between 0 and 5 images
then add 10 per image to score

if post contains more than 5 images
then ignore post

>     post_num_links_video, weight = -25

If post contains video links subtract 25 per video

 

>    author_repuation, weight = 1

if author reputation is 55 for example
then add 55 to score

   

>  post_has_english_language_use, weight = 50

if post is english
then add 50 to score

if post is not english,
then ignore post

**Thank you for your time! Forgive the silly questions please ;)**

**Comment by thrize** [comment]
Firstly, your confusion is founded, the value for word count should not be negative!

Otherwise your understanding is correct except on one important point - no post is ignored if the value of any metric is outside the given range.

For example you interpret the following metric settings:

> post_num_links_image in range 0 to 5, weight = 10

as

> if the post contains between 0 and 5 images
> then add 10 per image to score
> 
> if post contains more than 5 images
> then ignore post

The post is not ignored if there are more than 5 images, the score just does not increase. So for example, the following score will be added:

* if 4 images, add 40 points
* if 5 images, add 50 points
* if 6 images, add 50 points
* if 7 images, add 50 points

etc.

Does this make sense?

**Comment by Cam-B** [comment]
**Thank you.** Yes that example does make sense to me. 

Is this a typo then and the weight should = 0.5 instead of -0.5 ?

https://github.com/Steem-FOSSbot/steem-fossbot-voter/blob/master/docs/usage-guide.md

In your Example 1, "long form articles" the first metric is this:
`
post_num_words in range 200 to 600, weight = -0.5`


**Do I understand correctly now?**

If the first metric is 
`post_num_words in range 200 to 600, weight = 0.5`
then this metric will add an extra 0.5  score points per word as long as the post is in the 200-600 word range. If the post is below or over the 200-600 range it will ad no score points based on words.

**Comment by Cam-B** [comment]
If I do understand correctly now, then I think there are also some typos in example 2 
https://github.com/Steem-FOSSbot/steem-fossbot-voter/blob/master/docs/usage-guide.md
Is that right?

```
post_num_words, weight = -1
    post_images_only, weight = 500
    post_num_links_image, weight = 20
```

> So for every word we loose **5** score post. If the post is images only (less than 100 words) then we add **1000**, which is a lot but will high skew the score up for these kind of posts which we're mostly interested in. Additionally we add **100** for every image.

**This should be:**

> So for every word we loose **1** score point. If the post is images only (less than 100 words) then we add **500**, which is a lot but will high skew the score up for these kind of posts which we're mostly interested in. Additionally we add **20** for every image.

**Comment by thrize** [comment]
> Is this a typo then and the weight should = 0.5 instead of -0.5 ?

Yes, and it should be updated.

> If the first metric is
> ```post_num_words in range 200 to 600, weight = 0.5```
> then this metric will add an extra 0.5 score points per word as long as the post is in the 200-600 word range. If the post is below or over the 200-600 range it will ad no score points based on words.

No, this is not quite correct. If the post is below 200 it will add no score points, but if it is equal to or above 600 then it will add ```(600 - 200) * 0.5 = 200``` points. The score is still in effect if the metric value if **greater** than the upper bound of the range but it does not increase any more.

> If I do understand correctly now, then I think there are also some typos in example 2

🤦‍♂️  Yes you're right, the numbers are all wrong! Damn, I will have to fix this too, to what you corrected it to. You are free to do this correction yourself and submit as a pull request.

**Comment by Cam-B** [comment]
Thank you I finally get it. :)

I submitted the request. First time for everything. :) Also added a link to the docker version on the install page.

**Comment by Boontjie** [comment]
This is related I am not able to get the test algorithm to say VOTE = YES.  I pretty much deleted all the rules and applied the sellout from 'https://steemit.com/bots/@personz/a-new-voter-bot-newer-smarter-freer'
author_is_followed, weight = 1000
Well this author is followed but I get,

Post title | Score | Vote
-- | -- | --
BigPanda FIGHT CLUB Season 1: Round 2 Results | 1000 | NO

I don't understand how your scoring and example does not work

**Comment by thrize** [comment]
Me neither, I'll check it out.

I'm going to close this issue and open another one for that though @Boontjie
