### ISSUE TITLE
How to Vote Only Author with Reputation Range 30 to 60?

### ISSUE THREAD

**Issue by maxim888** [Steem-FOSSbot/steem-fossbot-voter#110]
How to Vote Only Author with Reputation Range 25 to 60? I just want to vote authors with reputation 25 to 60. I am able to filter authors with reputation 60 and above with setting below. 

author_repuation
Weight: -50000
Lower Bound: 60
Upper Bound: 100

But I can't filter out authors with reputation 25 and below. If I use setting below the scoring metric will go wrong. Those reputation with 25 to 60 will have negative score as well. 
author_repuation
Weight: -50000
Lower Bound: -50
Upper Bound: 25

Final method I tried is remove above two setting but giving positive score 10000 on authors with reputation 30 to 60. But this won't work too when combine with other scoring factors. Those who reputation 60 have much higher score than those reputation 30 from author_repuation. This will work only when all reputation 30 to 60 getting same 10000 score from author_repuation alone.

**Comment by thrize** [comment]
You need to set something positive. I suggest the exact opposite settings, push _up_ the score of posts with rep between 25 and 60, instead of pushing down other posts.

author_repuation
Weight: 100
Lower Bound: 25
Upper Bound: 60

**Comment by thrize** [comment]
Nothing more to do here, closing
