### ISSUE TITLE
How to play this.?

### ISSUE THREAD

**Issue by mustarzil** [Steem-FOSSbot/steem-fossbot-voter#112]
How ya How to play this program Since I just present in this program ,, please comment yes ,,, help me to be a great person like you guys ..
[steem-master.zip](https://github.com/Steem-FOSSbot/steem-fossbot-voter/files/1553148/steem-master.zip)

**Comment by thrize** [comment]
Em, can you detail what issue you're facing?

**Comment by thrize** [comment]
No response, closing
