### ISSUE TITLE
Cannot use SendGrid for two different bot instances on same Heroku account

### ISSUE THREAD

**Issue by poweruprewards** [Steem-FOSSbot/steem-fossbot-voter#113]
Its telling me my acct doesnt have permission for sendgrid add on..... When i just deleted a bot that was using it...???

**Comment by thrize** [comment]
Did you fix this?

**Comment by DrakahnF** [comment]
I sent a ticket to heroku about this, they never replied and closed the ticket.

Had to make a new heroku account.

**Comment by thrize** [comment]
@DrakahnF did making a new Heroku account fix it for you on the new account?

**Comment by DrakahnF** [comment]
I mean it seems that each account can only add sendgrid once, so if sendgrid is required then a second install is impossible, if I wanted to start again I would need a third account. 

Maybe just make a second install button that installs without sendgrid, for people that already have it on another bot/app and know the api key/etc to enter.

**Comment by thrize** [comment]
Oh, that is interesting, I didn't know that. Email notifications, and so SendGrid, is coming out in the 0.3 release (it's already complete in the develop branch on ticket #95) so this will become moot anyway.

I'm going to close since the feature is deprecated.
