### ISSUE TITLE
Stats page does not load

### ISSUE THREAD

**Issue by DrakahnF** [Steem-FOSSbot/steem-fossbot-voter#115]
This is what I get on the stats page now. After clicking on any time. I can still see the days votes but not the specific run.

{"status":500,"error":"/stats-data-json Server error","message":"stats-data-json: key 1f3416fd541bf68baede36c0618bca0a could not be fetched"}

**Comment by thrize** [comment]
I've seen this before, it's a problem with the database, it's reached it's capacity and is now getting corrupted because no additional data can be recorded.

This will be fixed by #64 which I am planning on getting back as soon as I can. Honestly, this will be done, I'm half way through it.
