### ISSUE TITLE
Test algorithm not working

### ISSUE THREAD

**Issue by thrize** [Steem-FOSSbot/steem-fossbot-voter#116]
_Moved from #107, comment of @Boontjie_

This is related I am not able to get the test algorithm to say VOTE = YES.  I pretty much deleted all the rules and applied the sellout from 'https://steemit.com/bots/@personz/a-new-voter-bot-newer-smarter-freer'
author_is_followed, weight = 1000
Well this author is followed but I get,

Post title | Score | Vote
-- | -- | --
BigPanda FIGHT CLUB Season 1: Round 2 Results | 1000 | NO

I don't understand how your scoring and example does not work

**Comment by CzarnaMamba** [comment]
I have similar issue, whatever config I set it's always VOTE = NO

**Comment by Milesolson** [comment]
I am only getting NO for everything too

**Comment by thrize** [comment]
Confirmed, there's a bug in this

**Comment by thrize** [comment]
Fixed in v0.3.0

**Comment by DavidFnck** [comment]
Wow, 3.0 released! Amazing Work! Should I redeploy it to Hreoku?

**Comment by thrize** [comment]
Yes but follow the installation instructions or you will lose your data because there is a database change

**Comment by 1rufaz** [comment]
I have this problem, fresh install today.

**Comment by thrize** [comment]
This is now resolved right @1rufaz ?

**Comment by 1rufaz** [comment]
No not resolved :(

**Comment by thrize** [comment]
This is definitely fixed, so it's some other issue influencing your difficulties, I'm not reopening this ticket
