### ISSUE TITLE
"version undefined"

### ISSUE THREAD

**Issue by DrakahnF** [Steem-FOSSbot/steem-fossbot-voter#118]
So, all I have gotten for the past couple of days is either app error or, 
"version undefined
Enter BOT_API_KEY here and section using the buttons below.
[And the enter key form]"

If I enter the key then it goes to 
"version undefined
Session is valid, dashboard active
[And the steemit/steemd links]"

I have tried rolling back to a working version on heroku with no luck, so I think it is another problem on the heroku side. 

I have also tried on a third account with a fresh install.

**Comment by bobinson** [comment]
#93  #102 has the same issue reported

**Comment by DrakahnF** [comment]
Oh I didn't see that one, sorry.

**Comment by thrize** [comment]
Thanks for reporting @DrakahnF . Yes this is a serious issue I'm investigating now, we'll track this in #93 so I'll close this as a duplicate.
