### ISSUE TITLE
Test algorithm working  but run bot not working

### ISSUE THREAD

**Issue by pranishg** [Steem-FOSSbot/steem-fossbot-voter#120]
hello
when i do test algorithm it works..but when i do run bot ---it gives error 
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

please help

**Comment by tangbiondi** [comment]
the same issue found. i followed the installation guide and deployed the app onto heroku. running the bot will always return application error no matter what algorithm defined. running test algorithm with the first 5 posts is fine.

**Comment by pranishg** [comment]
Hello ,
Since the bot scans a lot in the network that is why it is showing app error ..
it just votes fine 
simply add in heroku schedular and it will work 
if you manage multiple accounts then i have made a new bot 

https://github.com/pranishg/upvoting_bot_with-multiple-accounts

donate sbd or steem if you like my bot  @pranishg in steemit

**Comment by Xcoder89** [comment]
same issue! can't seem to get the bot working manually or through the scheduler (don't see any logs on Heroku dashboard)

**Comment by DavidFnck** [comment]
Same issue!

I have tried several ways:

1. paid for a Hobby Dynos and run every 10 mins, still error, as @pranishg said:

> simply add in heroku schedular and it will work

2. change the MAX_POST_TO_READ from 10 to 400, still error, it was mentioned by @thrize in #86

> This is something I'm aware of but put on the back burner. It is caused because the process is taking longer than the page load timeout time. It was okay when the bot was made originally because there was less activity but now it takes longer, particularly due to increasing MAX_POST_TO_READ (see #70).


At last I find the similar problem is under the the issue #86 , and @thrize had moved this from Review to In Progress in Maintenance 14 days ago. 

but now(**_Jan.22 2018_**) it's still in progress, let's wait for good news.

**Comment by thrize** [comment]
Good news will come soon, I'm hoping to release 0.3 this week and which should clear most of these bugs

**Comment by DavidFnck** [comment]
That's amazing! THANKS @thrize

**Comment by Xcoder89** [comment]
@thrize Thanks! Looking forward to it!

**Comment by thrize** [comment]
Duplicated by #116 which is now fixed
