### ISSUE TITLE
TUTORIAL IN ITALIANO

### ISSUE THREAD

**Issue by steempostbuilder** [Steem-FOSSbot/steem-fossbot-voter#125]
Hello everyone, I wanted to tell you my step by step guide in ITALIAN language.
I hope it may have been useful. More tutorials on some specific functions will follow.

Sorry for my english, Goggle Translate. :)

https://steemit.com/steemit/@steempostbuilder/fossbot-autovoter-bot-in-20-minuti-ita

**Comment by thrize** [comment]
Awesome, thank you for this.

I see you made it for v0.2.10 though, and now we have a big upgrade in v0.3.0

It's up to you but I would suggest that you remove the parts about SendGrid because that feature is now completely gone, though of course it will still continue to function in v0.2.x

**Comment by thrize** [comment]
Also, if you ever want to contribute any translations to the project for Italian we can figure something out to integrate them. 🙂

**Comment by steempostbuilder** [comment]
It means that I will do a tutorial that will explain the differences between version 2.0.10 and v30 making it clear why send grid will not be useful anymore :)

**Comment by steempostbuilder** [comment]
![4](https://user-images.githubusercontent.com/35899764/35651377-c9c49be2-06df-11e8-85f2-fd51435a35e5.JPG)

I would be honored ! ;)

**Comment by thrize** [comment]
> It means that I will do a tutorial that will explain the differences between version 2.0.10 and v30 making it clear why send grid will not be useful anymore :)

Good Idea :)

I've shared your post so I'm going to close this ticket now as it does not track a feature or report a bug. Thanks again.
