### ISSUE TITLE
Bot run does not work if following very few users or not following any

### ISSUE THREAD

**Issue by thrize** [Steem-FOSSbot/steem-fossbot-voter#128]
_Originally reported in #126_

There is some evidence that if the account user is following only a few users (e.g. 12) or none at all that the bot run does not start correctly.

**Comment by thrize** [comment]
You really need to get me some logs, can you do that @1rufaz ?

**Comment by thrize** [comment]
How about them logs?

**Comment by 1rufaz** [comment]
I don't know how to do that, it tells me the log files are empty.

**Comment by scottiesan** [comment]
I had the same problem.  It get stuck in an infinite loop of getting followed user.  It work for me after flowing more user.  100+ follow users.

**Comment by thrize** [comment]
I'm looking into it

**Comment by thrize** [comment]
I tried to reproduce this on an account which is following no users and is not followed by any users

```
getFollowers_recursive, got 0 results
getFollowers_recursive, followers in result: []
getFollowers_recursive, followers now 0
getFollowers_recursive, finished
getFollowers_recursive, followers: []
getFollowing
<<account>> follows: 
```

I also tried on an account which is following 4 accounts:

```
getFollowers_recursive, got 4 results
getFollowers_recursive, followers in result: <<JSON>>
getFollowers_recursive, followers now 4
getFollowers_recursive, finished
getFollowers_recursive, followers: <<list>>
getFollowing
<<account>> follows: codingpanda,pangur-ban,taoofsatoshi,utfull
```

It worked fine. Guess it's something else that's causing it. I'm not going to close this right now but I'll put it in review. You guys should check it again when the next release v3.2 is out, I'll remind you.

**Comment by thrize** [comment]
This is ready to retest now guys, @1rufaz and @scottiesan holla back

**Comment by thrize** [comment]
I'm going to consider this fixed if I don't hear from you guys.

Also followers might be a red herring, you might be experiencing this issue described in #149, although I haven't confirmed it's an issue

**Comment by thrize** [comment]
@1rufaz and @scottiesan , last chance to check this out
