### ISSUE TITLE
curation trail setup on heroku

### ISSUE THREAD

**Issue by fractalnode** [Steem-FOSSbot/steem-fossbot-voter#130]
I would like to be able to vote on posts just like a selected group of accounts. These people can cast their votes a few days after the release of the post. At the moment I can only vote on posts that appeared ~ 30 min ago and check out about 800 posts. Larger numbers in these parameters make the application not work. This causes that parameters such as "post_up_voted_num_whitelisted" do not fulfill their function.

**Comment by thrize** [comment]
True @fractalnode , the posts scanning system needs to be updated. I'm hoping to deal with that as part of feature #96

**Comment by thrize** [comment]
@fractalnode with added stability I hope that setting a large value for `MAX_POST_TO_READ` will work for you.

If there is a specific bug (you say using a large number for `MAX_POST_TO_READ` causes the bot not to work), then please log it as a bug when v3.2 of the bot is released soon.
