### ISSUE TITLE
Author blacklist / Whitelist / is Followed vars do not work

### ISSUE THREAD

**Issue by prosmacs** [Steem-FOSSbot/steem-fossbot-voter#133]
Since a while i have noticed that the rule  author_is_blacklisted does not work anymore. I have the same issue for author_is_whitelisted and author_is_followed. I noticed the issue, when i saw that authors still get votes after i blacklisted them. So i checked the stats. I saw than that also whitelisted authors and followed authors get no points even tough i assigned them 15 ponts for whitlisted and 7,5 for followed. Blacklisted authors i assigned -75 points which should exlude them from votes.
As you can see here in my screenshot the concerning mettrics do not show up in the chart, also treshold is very low.  http://fs1.directupload.net/images/180407/pdbyd8wv.png.
I wrote this three issues in one ticket because they all have in common that they concern lists of author. So i concluded that they have one common cause.

**Comment by thrize** [comment]
Great, thanks for sharing this issue, I'll investigate it now

**Comment by thrize** [comment]
Turns out the issue is in getting the account from the Steemit API

`error, can't get user accounts: FetchError: invalid json response body at https://api.steemit.com reason: Unexpected token < in JSON at position 0`

Will fix

**Comment by thrize** [comment]
Basic use case is fixed, should test this a lot

**Comment by thrize** [comment]
Available in v0.3.2
