### ISSUE TITLE
only voting for white listed accounts

### ISSUE THREAD

**Issue by kena-kwasi** [Steem-FOSSbot/steem-fossbot-voter#147]
If I only want to vote for white listed accounts, is this possible in current algorithm? If yes how can I get this done.

**Comment by kena-kwasi** [comment]
@thrize any feedback on this?

**Comment by thrize** [comment]
Check out the usage guide: https://github.com/Steem-FOSSbot/steem-fossbot-voter/blob/master/docs/usage-guide.md
