### ISSUE TITLE
how to control my voting power?

### ISSUE THREAD

**Issue by chenlocus** [Steem-FOSSbot/steem-fossbot-voter#150]
I cannot find any place for me to adjust voting power, e.g. I want to vote 12% of my voting power to certain posts?

**Comment by thrize** [comment]
You should read the [Config Var section of the algorithm guide](https://github.com/Steem-FOSSbot/steem-fossbot-voter/blob/master/docs/algorithm.md#standard). The Config Var you are looking for is ```VOTE_VOTING_POWER```, and you set it in the Edit Config section of the web app.

You cannot set it for "certain posts", it is for all posts.
