### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by Netherdrake** [Steem-FOSSbot/steem-fossbot-voter#34]
Hi personz,

I have just discovered your project trough github tags, and I would like to tell you how awesome it is.

I love the beautiful d3 charts, amazing documentation and the licensing choice. I see and feel the love you've put into the project, and I'm looking forward to its success.

Please let me know when the new release is ready, and I will re-steem the announcement as well as share it with the whales.

Cheers,

@furion

**Comment by thrize** [comment]
Thank you! Great to hear people are enjoying it.

There will be a general bug fix patch release to be finished by the end of the month, tracked as [milestone 1](https://github.com/Steem-FOSSbot/steem-fossbot-voter/milestone/1)

Then I will be implementing new features for [milestone 2](https://github.com/Steem-FOSSbot/steem-fossbot-voter/milestone/3) which could run into April.

There is a Golos fork in the works too with no set date.

If you have any suggestions for features or find any bug people log them here.

Thanks again! Watch the [(at)personz](https://steemit.com/@personz) account on the 1st of March for planned next release, or in general for other stuff, up to you ;)

Oh, last thing, if you ever develop anything for Steem that fits the FOSS model, or what to get involved in one of the existing projects, please get in touch!
