### ISSUE TITLE
Should optionally vote on more that last 100 posts

### ISSUE THREAD

**Issue by thrize** [Steem-FOSSbot/steem-fossbot-voter#39]
On first run the option should be given to run on more than the last 100 newest posts.

Not sure how best to present this option to the user though?

**Comment by thrize** [comment]
Suggested by Steemit user (at)beeskee

**Comment by thrize** [comment]
Changed title, the option should be for any bot run, not just the first one.

It seems best left as a default and then allow user to customise as a config variable.

Could increase the default from 100 to 500 or even 1000, but would have to make sure processing per day is kept low / short enough.

**Comment by shaunmza** [comment]
I tried manually editing it to 200 on my heroku instance and the bot just crashed.

Think too much and it runs out of memory, could be lying as I never checked the logs, just set it back to 100.

**Comment by thrize** [comment]
I actually duplicated this by accident in #44 

Yep it crashes, the actual call won't accept more than 100 max, so fails. You have to call it multiple times and "page" the data. This is now implemented, you can check out branch bugfixes/thrize for the preview, will be merged into develop probably today or tomorrow

**Comment by thrize** [comment]
Closing duplicate
