### ISSUE TITLE
When running bot.js, it does not exit when done

### ISSUE THREAD

**Issue by shaunmza** [Steem-FOSSbot/steem-fossbot-voter#53]
When running bot.js manually, it never seems to exit when done.

command is `node bot.js`

Expected behaviour is that the bot exits on completion

**Comment by thrize** [comment]
Fixed pending review

**Comment by thrize** [comment]
Confirmed fixed

**Comment by thrize** [comment]
Introduced bug, process exits before all anonymous functions have completed. Need to only trigger callback when done _in the case of local run only_. Web app frontend run should not wait.

**Comment by thrize** [comment]
Fixed pending review

**Comment by thrize** [comment]
Okay I've cracked it @shaunmza , tested and works

**Comment by thrize** [comment]
Premature closing again, more fixes required to get this working consistently

**Comment by thrize** [comment]
Finally fixed

**Comment by thrize** [comment]
I have to admit there may be a few loose ends with this so keep an eye on it and close when the first round of bugfixing is finished if there are no more problems

**Comment by thrize** [comment]
@shaunmza have you seen any issue with this recently? I'm hoping it's been enough time now for us to determine whether or not the latest fix has worked

**Comment by thrize** [comment]
I believe this is working correctly as of v0.2.8
