### ISSUE TITLE
running locally or on VPS?

### ISSUE THREAD

**Issue by Stoner19** [Steem-FOSSbot/steem-fossbot-voter#61]
Anyone have instructions on running this locally or on a VPS so it doesn't have to be deployed to heroku?

**Comment by thrize** [comment]
This duplicates #9 but it's actually already done, the docs just aren't updated yet.

We have the [voter-docker](https://github.com/Steem-FOSSbot/voter-docker) project which takes care of this, and a [tutorial on Steemit](https://steemit.com/bots/@personz/docker-voter-automatic-easy-local-install-for-steem-fossbot-voter) to get you running.

It will run locally on any machine that can run docker, as well as any VPS that can run docker.

#9 will be updated very soon, along with the docs.

**Comment by Stoner19** [comment]
Thank you @thrize I'll take a look at the links you shared.
