### ISSUE TITLE
Blacklist does not work

### ISSUE THREAD

**Issue by thrize** [Steem-FOSSbot/steem-fossbot-voter#62]
Blacklist does not appear to work. Need investigation.

Discovered by @shaunmza

**Comment by thrize** [comment]
Finally discovered why this is happening. The initialization of steem variables does not wait until completion before running the main bot logic when run via bot.js, i.e. when scheduled.

Need to use a promise / callback to wait for completion before running main bot logic.

**Comment by shaunmza** [comment]
I noticed when exporting the configs, that the values for blacklist category and blacklist user are concatenated into a string i.e. ["a b c"] and not into an array ["a", "b", "c"] as I expected it should be.

Editing these values manually and re-importing the configs seems to have sorted this issue out.

**Comment by thrize** [comment]
@shaunmza I cannot replicate that, can you please recheck and provide more detail if it is still happening for you?

**Comment by thrize** [comment]
I've confirmed that this works, so I'm going to move it along for the sake of getting 0.2.8, though please do check and comment if there is something I'm missing here

**Comment by thrize** [comment]
Fixed in v0.2.8
