### ISSUE TITLE
Switch DB from Redis to MongoDB

### ISSUE THREAD

**Issue by thrize** [Steem-FOSSbot/steem-fossbot-voter#64]
I regret not starting off with MongoDB, I thought it would be simpler using Redis. I was wrong, I've basically ended up replicating the features MongoDB automatically provide and have not done a good enough job at it.

It seems the system will run out of memory and the fail safe features I'd written for it are not working.

E.g.

```
2017-05-21T19:02:08.187196+00:00 app[web.1]: savePostsMetadata
2017-05-21T19:02:08.188358+00:00 app[web.1]: persistJson save for key daily_liked_posts
2017-05-21T19:02:08.188361+00:00 app[web.1]: setError to "started" , persistJson redis error for key daily_liked_posts: OOM command not allowed when used memory > 'maxmemory'.
2017-05-21T19:02:08.188361+00:00 app[web.1]: ERROR, addDailyLikedPost failed to be saved
```

Rather than fix it, I think it would be best to switch to MongoDB

### Impact

**This is a serious fundamental change which will require all old bots to be manually redeployed.** New code will not work by just upgrading the codebase, users will need to delete their current instance and deploy.

This will also affect the [voter-docker](https://github.com/Steem-FOSSbot/voter-docker) deployment as it is configured to set up a Redis DB on a separate image. @shaunmza will need to be consulted when this change comes into effect

**Comment by thrize** [comment]
This is high priority so moving it along

**Comment by thrize** [comment]
Wow that's a lot of commits! This is finally looking stable, I just need to test out every path and do some other maintenance but almost ready to sign off of this feature.

**Comment by thrize** [comment]
Done, to be included in v0.3.0

**Comment by DavidFnck** [comment]
Cheers！Should I deploy it to Heroku again? I don't find v0.3.0.

I find the application can open recently.

**Comment by thrize** [comment]
It's not put together yet dude, just give me a few hours.

**Comment by DavidFnck** [comment]
Thank you for your hard work, that's quite amazing. I want to upvote to your article everytime.

**Comment by thrize** [comment]
Well I found a few related bugs so it will be a little longer, but I'm hoping to release 0.3 within 24 hours

**Comment by thrize** [comment]
Confirmed fixed
