### ISSUE TITLE
Add voting power conservation

### ISSUE THREAD

**Issue by thrize** [Steem-FOSSbot/steem-fossbot-voter#7]
Currently, when counting the number of votes cast in the last 24 hours, the bot counts the _total_, which includes up votes and down votes.

I'm not sure what the best way of handling this would be, but I think an adjustment should be made.

Since the bot is concerned only with up voting, perhaps only the up votes should be counted.

However, since down voting reduces voting power, perhaps they should be counted. But maybe separately?

From a voting power conservation / wise usage perspective,  maybe instead restricting voting (by threshold adjustment) using number of votes per day, it would be better to use the change in voting power directly?

**Comment by thrize** [comment]
I've also realised the vote counting counts votes on comments, of course. With the (at)asshole account down voting comments, effectively flagging and removing their visiblity, for the moment up voting comments is the way to go.

This further makes me think it should be about conserving voting power, as that's really what the vote limiting is about.

It also bring the case of being able to set voting power when up voting with the bot, but that's should be raised separately.

**Comment by ubgg** [comment]
Make the bot keep the voting power x>% also add variables as to how frequently the bot will vote on what voting power. For example if the voting power is close to x then it would be more conservative then it would be with full voting power.

**Comment by thrize** [comment]
Great idea. Here's how I propose developing that.

![vote_power](https://cloud.githubusercontent.com/assets/25388336/22534606/dad6c5ca-e8d3-11e6-93fa-494e274b5eae.png)

On the y-axis we have **Power on vote**, which is the power to be used when casting a vote. Currently for the bot this is always 100%.

On the x-axis we have the users current **Voting power**, as the Steem blockchain reports it.

So we need three variables to allow for a dynamic setting of voting power. This is the one you suggest plus two other which are:

1. Minimum voting power (as you suggested), in the graph at 70%, the minimum the blue line can be.
2. Voting power curbing threshold, in the graph at 80%, shown by the yellow-orange line
3. Voting power curbing limit, in the graph at 50%, shown by the red line

While voting power is above the _voting power curbing threshold_, voting power on votes will remain at 100%. When voting power hits the _voting power curbing threshold_, voting power reduces with linear interpolation (i.e. a straight line) until voting power hits the _voting power curbing limit_. If the voting power goes below this limit, voting can then stop.

It could work in tandem with the number of votes per day limit, as in the current implementation, but what do you think of this idea?

**Comment by thrize** [comment]
This Steemit article looks to be very instructive https://steemit.com/voting/@biophil/the-complete-definitive-and-yes-ultimate-guide-to-voting-power-updated

**Comment by thrize** [comment]
Hey @ubgg do you want to comment on this? Getting ready to implement soon 🙂

**Comment by thrize** [comment]
Both @shaunmza and @norganna have forks which implement a hardcoded, ad hoc vote power setting. This has to be implemented! I'll prioritize it 😉

**Comment by thrize** [comment]
Change of plans for this ticket.

Instead of changing the voting power gradually (as I believe the more widely useful use case is constant voting power for on votes cast) it is the threshold which should be changed gradually as voting power decreases from 100% and approaches ```MIN_VOTING_POWER```.

Ticket #90 completely removed the additional score threshold adjustment. This should be reinstated further to the change made in #87 (adding ```MIN_VOTING_POWER``` and ```VOTE_VOTING_POWER``` config vars with implementation).

**Comment by thrize** [comment]
Voting and scoring now needs to be rolled into the same loop as voting power changes with each vote and is important to be taken into account _as each vote is made_.

Also I think the power throttling should perhaps be optional.

**Comment by thrize** [comment]
Tested and working. In v0.2.9

**Comment by thrize** [comment]
Need to update docs for threshold increase based on voting power approaching min
