### ISSUE TITLE
Clarify docs on generating BOT_API_KEY

### ISSUE THREAD

**Issue by imkimchi** [Steem-FOSSbot/steem-fossbot-voter#75]
Should I manually generate one? The documentation doesn't specify whether I should generate one or what api key is.

**Comment by thrize** [comment]
From the installation docs:

> BOT_API_KEY, set to any alphanumeric key you generate to grant access to your bot. Used to authenticate bot actions, such as start bot, as well as third party access.

I think I will reword that slightly to make it super clear, but you have to generate the key yourself.

I would advise that you do not generate it on a website, you should generate it locally. I recommend [OpenSSL](https://wiki.openssl.org/index.php/Binaries) which is available for any OS.

From the command line you can type the following to get a 24 digit hex number

```openssl rand 24 -hex```

**Comment by thrize** [comment]
Fixed for v0.2.10
