### ISSUE TITLE
Post age time

### ISSUE THREAD

**Issue by 1rufaz** [Steem-FOSSbot/steem-fossbot-voter#84]
I set the age time to 1440 to 2880, it didn't return any requests.

Am I right in thinking it pulls the latest 400 posts?

Otherwise it will be pulling posts from last year!

**Comment by thrize** [comment]
It will only fetch a maximum number of posts which is set by the config variable ```MAX_POST_TO_READ ``` (more info [here](https://github.com/Steem-FOSSbot/steem-fossbot-voter/blob/master/docs/algorithm.md#settings-and-constants)). Currently the default is `400`. You can set this in the [Edit Config](https://github.com/Steem-FOSSbot/steem-fossbot-voter/blob/master/docs/dashboard-overview.md#4-edit-config) page.

But you're right, if you set the age time wrong it will reject anything _younger_ than that age. If you set the age to 1440 or 2880, that is defined in **minutes**, so with those values you are saying _do not consider anything younger than 24 or 48 hours_ (respectively).

If that is correctly your intention you will need to fetch many more posts! I'm not sure how many posts are posted daily but last time I checked it was in the thousands, around 5000. If you set ```MAX_POST_TO_READ``` to 15000 for example, it should technically work but it will take a really long time and the process will take significantly more memory as those fetched posts are held in memory and not optimized for large fetches.
