### ISSUE TITLE
User setting for constant voting power

### ISSUE THREAD

**Issue by Pablito7373** [Steem-FOSSbot/steem-fossbot-voter#87]
Hi everyone, I just installed the fosserbot, everything works well even though I have put some to install it but considering the fact that I'm not a computer I can feel more satisfied.
I would have a question, if I wanted to give my votes at 50% and not 100%, or would I decide to vote for my whitelist at 30% would it be possible?
Is it possible to change the percentage of voting power?

**Comment by ausbitbank** [comment]
You can edit lib.js line 1291 and change the "10000" to "5000" to vote at 50% power instead of 100%

https://github.com/Steem-FOSSbot/steem-fossbot-voter/blob/master/lib.js

**Comment by thrize** [comment]
Thanks for helping @Pablito7373 out @ausbitbank 

This is of course a hack that you can use for the moment. I'n going to make a quick feature addition for this though (setting vote power) as while I hoped to implement ticket #7 (Add voting power conservation) sooner, and it would be a more robust solution, this feature is the most requested one.

I hope to have a basic implementation added within a day.

**Comment by thrize** [comment]
@Pablito7373 I'm changing the name of this ticket to reflect the general case

**Comment by Pablito7373** [comment]
This is a good news, I've also made some report changes that are sent via email, deleted all information regarding configuration and data algorithm. Thank you very much for the availability. Thank you all

**Comment by thrize** [comment]
This is now working. Will be in v0.2.9 release
