### ISSUE TITLE
help

### ISSUE THREAD

**Issue by paulsusanta** [Steem-FOSSbot/steem-fossbot-voter#89]
can i set some profile of my steemit followings and when they upload a new post the bot will instantly upvote the post reply soon..

**Comment by thrize** [comment]
Yes you can do this. You set up the bot as usual and then use the ```author_is_followed``` metric _only_.

This exact use case is actually the [third example](https://github.com/Steem-FOSSbot/steem-fossbot-voter/blob/master/docs/usage-guide.md#example-3-the-sell-out) in the [usage guide](https://github.com/Steem-FOSSbot/steem-fossbot-voter/blob/master/docs/usage-guide.md).
