### ISSUE TITLE
heroku requires a CC to install.. :(

### ISSUE THREAD

**Issue by stresskiller** [Steem-FOSSbot/steem-fossbot-voter#91]
is there a way to install this on a webserver without heroku since i don't have acces to a Creditcard i can't use heroku for it.

**Comment by thrize** [comment]
You could use a docker deployment based on the [voter-docker](https://github.com/Steem-FOSSbot/voter-docker) deployment.

Otherwise you can deploy the code to any Node enabled service with Redis (e.g. RedHat's OpenShift), but you'll need to make some small code changes.
