### ISSUE TITLE
Feature Request: Post a comment on voted for posts

### ISSUE THREAD

**Issue by juicypop** [Steem-FOSSbot/steem-fossbot-voter#92]
Would it be possible to add the option of our unique comment on each upvote we give?

This would be totaly awesome if we could let other know that we use fossbot-voter :)

**Comment by rkoconsult** [comment]
Great suggestion! I would love to have that feature…

**Comment by thrize** [comment]
Nice idea. I think this is potentially a cool feature, but I do worry that it would just add more spam to the network. However if it is considered to be spam the accounts making the spam will be the ones targeted so maybe it's not for me to say if it's spam or not.

Leaning towards a yes :)

**Comment by juicypop** [comment]
I think this would also depend on your personal message your voter bot posts in your name

Sometimes leaving a neat comment reminds followers to check your blog too, that's what I intend to do with it :D

Would be great to see this feature ;)

**Comment by thrize** [comment]
Okay, let's add it to the new features backlog. I'll ask for feedback in a future blog post.

If you want to help with this you could start imagining how it might work in detail :)

**Comment by juicypop** [comment]
Thanks a lot!

Yes I might work out a concept and post it. Where would be the right place to post it? Just here in comments or do you prefer a steemit post about it? :D

**Comment by thrize** [comment]
Whatever you like, either is fine. :)

**Comment by juicypop** [comment]
That's cool, I will prepare something and post it ;)

I searched on steemit and found personz, the coder, but I couldn't find you thrize, would like to follow you as well :)

**Comment by thrize** [comment]
personz = thrize ;)

**Comment by juicypop** [comment]
Haha ok, good to know ;)

**Comment by Cam-B** [comment]
I would like this feature too. @camb on Steem

**Comment by Cam-B** [comment]
bottymcbotface sends a small tip with every comment as well to make sure he's not so annoying :)

**Comment by juicypop** [comment]
Finally I found some time to write a post about my feature request with 3 screenshots and small descriptions. 
You can find it here:
https://steemit.com/fossbot/@juicypop/fossbot-feature-request-post-comment-on-upvote-2017910t131534425z

I hope it meets your requirements :)

Have a nice sunday!

**Comment by thrize** [comment]
Thank you. For reference here they are:

### Dashboard UI

![](https://steemitimages.com/0x0/https://steemitimages.com/DQmQVV72LRLLVLfuZPWeNGdnd2hgautDjVdtve3PxfvEiBc/Dashboard_Comment.png)

### Detail UI

![](https://steemitimages.com/0x0/https://steemitimages.com/DQmeFuaa3AEnnid1rLuG9kS6LUoH8T295RCEyKoJmwQVrQp/Edit_Comment.png)

### Additionally

As it will be optional, it should also appear as a Config Var which can be either on or off. Or perhaps it is fine that if any text exists there at all then it should be active?

**Comment by juicypop** [comment]
Yes I forgot about that one. I think this would be the easiest option:
No comment text/content = posting comments off
Comment text/content filled = posting comments on (optional checking the rules, which are just 3 proposals I made on the Screenshot)

**Comment by thrize** [comment]
On this condition for comments to be active, I agree.

However I didn't see that the rules are related in some way to the comments. This does not make sense to me and seems complexifying. Can you clarify this?

**Comment by juicypop** [comment]
Sure I can. I just thought that we could set some rules wether a comment should be posted or not - just like wether a vote should be casted.

One may have different point of view if someone should receive a comment. The 3 above are just examples. I think it would be fine if we go with the same rules as the votes already go.

I hope this is understandable enough :D

By the way this was just an optional add-on, it's not necessary if it would complicate implementing comments at all ;)

**Comment by thrize** [comment]
I think that is probably too much, either it should comment on the posts you vote on or not at all.

If you really want it maybe make another ticket to track it as add-on feature, as you say.

**Comment by juicypop** [comment]
Ok no problem, having comments at all would enrich your bot by far :)

**Comment by braydengerrard** [comment]
Do we have any updates on this feature?  I would love to see this one implemented.

**Comment by nathenial90** [comment]
I also would love to know if it was completed? just a simple text message on every upvote would work

**Comment by thrize** [comment]
Okay, this is accepted. After release of v0.3 it will be on the list of new features to implement

**Comment by btcalttrader** [comment]
last version there is no comment option. how can we activate

**Comment by thrize** [comment]
@btcalttrader it has not been coded yet, you'll have to wait or you or anyone can implement it and submit it as a pull request

**Comment by btcalttrader** [comment]
yeah. thanks a lot dude. can we use now ?

**Comment by thrize** [comment]
No!

**Comment by btcalttrader** [comment]
thanks dude you are awesome

**Comment by ltbongo** [comment]
This came at the perfect time for me. Working perfectly so far

**Comment by thrize** [comment]
Available in v0.3.2
