### ISSUE TITLE
Task: switch to sequential scanning of posts so no posts are missed

### ISSUE THREAD

**Issue by thrize** [Steem-FOSSbot/steem-fossbot-voter#96]
The current system of requiring users to balance ```MAX_POST_TO_READ``` with ```MIN_POST_AGE_TO_CONSIDER``` to make sure all the last posts are read is very unfair and does not result in all posts always being processed.

Ideally every post is processed, even if it means that the bot is not completely up to date when it runs.

## Proposal

Switch from ```MAX_POST_TO_READ``` specifying the maximum number of posts to read _back from the current newest post on chain_ to specifying the maximum numbers of posts to read _from the last read post_.

### Edge cases

1. If the bot has not been run before, just read back ```MAX_POST_TO_READ``` number of posts from the newest posts.

### Notes

* This does not require any UI updates, or updates to config variables, only server code
* It can be considered a bug as it probably does not act the way users expect right now

**Comment by bobinson** [comment]
much needed improvement

**Comment by thrize** [comment]
Moved to features, will be done next on 0.3.0, I agree @bobinson , it's very needed

**Comment by thrize** [comment]
Removed bug label, on consideration it's not actually a bug, it's just a failing of the original post processing method

**Comment by Cam-B** [comment]
Doesn't this create a situation where a bot with limited resources might quickly fall far behind in processing posts?

**Comment by thrize** [comment]
Aw man of course you're right... you would have to run the bot quite frequently for that to work out, or set a limit on how far back in time to go, which is almost the same as the situation now.

Perhaps it would be better to keep getting posts from the blockchain and only _start_ counting the number of posts to process (```MAX_POST_TO_READ```) after the first post at ```MIN_POST_AGE_TO_CONSIDER``` number of minutes is reached, but after the last one you processed before. This would possibly give you the maximum number of posts to actually process and see the most original content.

**Comment by Cam-B** [comment]
Someone running the bot purely for financial gain will want to make sure that he has enough resources to not miss any posts. And in that case these changes would probably be essential 

Someone running the bot for more philanthropic reasons might prefer to run their bot it without these changes.

On that note. let me see if I can find you on https://utopian.io

**Comment by fractalnode** [comment]
I would prefer the bot to process posts from the timestamp to the timestamp. For example, from 4d to 4d + 1h, every 1 hour. Posts earlier than 4d, i.e. those out of range, should not be analyzed and should not consume resources

**Comment by thrize** [comment]
@fractalnode please make a detailed feature request for that

**Comment by fractalnode** [comment]
perhaps it would be possible to replace existing MAX_POST_TO_READ with the new MAX_POST_AGE_TO_CONSIDER 
then I could set the parameters this way
MIN_POST_AGE_TO_CONSIDER 5760 _(4 x 24 x 60)_
MAX_POST_AGE_TO_CONSIDER 5820 _(4 x 24 x 60) + 60_

**Comment by fractalnode** [comment]
English i not my first language also I'll try to be as concise as possible
I would like the logic that I set in the options to analyze posts that have 3-5 days instead of 30-40 minutes. At the moment it seems not possible at least on heroku

**Comment by thrize** [comment]
I'm not going to implement this, I've been talking to some other guys who just use a really big number for `MAX_POST_TO_READ` config variable and run it very often, every 10 minutes. This is the use case for people who want to run it continuously.

Running block to block is a very different way of operating.

Sorry guys, it's not the main usage case, I'm closing this ticket.
